apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvideo-web
  labels:
    needs-pull-secret: private
spec:
  selector:
    matchLabels:
      app: nvideo-web
  replicas: 1
  template:
    metadata:
      labels:
        app: nvideo-web
    spec:
      nodeSelector:
        nvideo-server: "true"
      containers:
      - name: nvideo-web
        image: nvideo-web-image-name-placeholder # kustomize
        imagePullPolicy: Always
        ports:
        - containerPort: 8000
        env:
        - name: API_PROTO
          value: http # internal
        - name: API_HOST
          value: "nvideo-api-svc"
        - name: API_PORT
          value: "80"
        - name: API_PATH
          value: /placeholder
        - name: WEB_GRAFANA_DASHBOARD_URL
          valueFrom:
            configMapKeyRef:
              name: nvideo-web-config
              key: dashboard-url
        - name: WEB_MAX_VIDEO_DURATION_SECONDS
          valueFrom:
            configMapKeyRef:
              name: nvideo-web-config
              key: max-video-duration-seconds
        - name: WEB_YOUTUBE_API_KEY
          valueFrom:
            secretKeyRef:
              name: nvideo-youtube-secret
              key: api-key
              optional: false

        # rabbitmq
        - name: RABBITMQ_PASS
          valueFrom:
            secretKeyRef:
              name: nvideo-rabbitmq-secret
              key: password
              optional: false
        - name: RABBITMQ_USER
          valueFrom:
            secretKeyRef:
              name: nvideo-rabbitmq-secret
              key: user
              optional: false
        - name: RABBITMQ_HOST
          value: nvideo-rabbitmq-svc
        - name: RABBITMQ_PORT
          value: "5672"
        - name: RABBITMQ_PROTO
          value: "amqp"
        resources:
          requests:
            memory: 128Mi
      imagePullSecrets:
      - name: registry-secret-name-placeholder # kustomize