apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - "namespace.yaml"

  - "api/deployment.yaml"
  - "api/httproute.yaml"
  - "api/service.yaml"
  - "api/podmonitor.yaml"

  - "web/deployment.yaml"
  - "web/httproute.yaml"
  - "web/service.yaml"

  - "postgres/deployment.yaml"
  - "postgres/pvc.yaml"
  - "postgres/service.yaml"

  - "rabbitmq/deployment.yaml"
  - "rabbitmq/pvc.yaml"
  - "rabbitmq/service.yaml"
  - "rabbitmq/tcproute.yaml"

  - "remote-transcription/deployment.yaml"

  - "remote-language/deployment.yaml"

  - "local-graph/deployment.yaml"
  - "local-graph/pvc.yaml"

namespace: nvideo