apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

nameSuffix: -gemini

resources:
  - ../../base/remote-language
  - ../../base/remote-transcription

patches:
  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nvideo-remote-language
      spec:
        template:
          spec:
            containers:
            - name: nvideo-remote-language
              env:
              - name: REMOTE_LANGUAGE_MODEL_PROVIDER
                value: "google"
                valueFrom: null
              - name: REMOTE_LANGUAGE_MODEL
                value: "gemini-flash-lite-latest"
                valueFrom: null
              - name: REMOTE_LANGUAGE_MODEL_PROVIDER_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: nvideo-language-secret-gemini
                    key: api-key

  - patch: |-
      apiVersion: apps/v1
      kind: Deployment
      metadata:
        name: nvideo-remote-transcription
      spec:
        template:
          spec:
            containers:
            - name: nvideo-remote-transcription
              env:
              - name: REMOTE_TRANSCRIPTION_PROVIDER
                value: "google"
                valueFrom: null
              - name: REMOTE_TRANSCRIPTION_MODEL
                value: "gemini-flash-lite-latest"
                valueFrom: null
              - name: REMOTE_TRANSCRIPTION_PROVIDER_API_KEY
                valueFrom:
                  secretKeyRef:
                    name: nvideo-transcription-secret-gemini
                    key: api-key