apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization


resources:
- ../base

namespace: nvideo-prod

images:
- name: nvideo-api-image-name-placeholder
  newName: registry.deeplerg.dev/nvideo-api
  newTag: main-b416bf6f
- name: nvideo-local-graph-image-name-placeholder
- name: nvideo-remote-language-image-name-placeholder
- name: nvideo-remote-transcription-image-name-placeholder
- name: nvideo-web-image-name-placeholder
  newName: registry.deeplerg.dev/nvideo-web
  newTag: main-b416bf6f

configMapGenerator:
- behavior: create
  envs:
  - environment-variables.env
  name: environment-variables







replacements:
- source:
    fieldPath: data.REGISTRY_CRED_NAME
    kind: ConfigMap
    name: environment-variables
  targets:
  - fieldPaths:
    - spec.template.spec.imagePullSecrets.[name=registry-secret-name-placeholder].name
    select:
      kind: Deployment
      labelSelector: needs-pull-secret=private
- source:
    fieldPath: data.NAME_FOR_GATEWAY
    kind: ConfigMap
    name: environment-variables
  targets:
  - fieldPaths:
    - metadata.labels.name-for-gateway
    select:
      kind: Namespace
  - fieldPaths:
    - metadata.labels.name-for-gateway
    select:
      kind: TCPRoute
- source:
    fieldPath: data.GATEWAY_NAME
    kind: ConfigMap
    name: environment-variables
  targets:
  - fieldPaths:
    - spec.parentRefs.0.name
    select:
      kind: HTTPRoute
  - fieldPaths:
    - spec.parentRefs.0.name
    select:
      kind: TCPRoute
- source:
    fieldPath: data.GATEWAY_NAMESPACE
    kind: ConfigMap
    name: environment-variables
  targets:
  - fieldPaths:
    - spec.parentRefs.0.namespace
    select:
      kind: HTTPRoute
  - fieldPaths:
    - spec.parentRefs.0.namespace
    select:
      kind: TCPRoute
- source:
    fieldPath: data.GATEWAY_HOST_API
    kind: ConfigMap
    name: environment-variables
  targets:
  - fieldPaths:
    - spec.hostnames.0
    select:
      kind: HTTPRoute
      labelSelector: nvideo/route-for=api
- source:
    fieldPath: data.GATEWAY_HOST_WEB
    kind: ConfigMap
    name: environment-variables
  targets:
  - fieldPaths:
    - spec.hostnames.0
    select:
      kind: HTTPRoute
      labelSelector: nvideo/route-for=web
- source:
    fieldPath: data.GATEWAY_PATH_API
    kind: ConfigMap
    name: environment-variables
  targets:
  - fieldPaths:
    - spec.rules.0.matches.0.path.value
    select:
      kind: HTTPRoute
      labelSelector: nvideo/route-for=api
  - fieldPaths:
    - spec.template.spec.containers.[name=nvideo-api].env.[name=API_PATH].value
    select:
      kind: Deployment
      name: nvideo-api
  - fieldPaths:
    - spec.template.spec.containers.[name=nvideo-web].env.[name=API_PATH].value
    select:
      kind: Deployment
      name: nvideo-web
