apiVersion: apps/v1
kind: Deployment
metadata:
  name: nvideo-postgres
spec:
  selector:
    matchLabels:
      app: nvideo-postgres
  replicas: 1 # replicas
  template:
    metadata:
      labels:
        app: nvideo-postgres
    spec:
      nodeSelector:
        main-ingress: "true"
      containers:
      - name: postgres
        image: postgres:16-alpine
        ports:
        - containerPort: 5432
        resources:
          requests:
            memory: "32Mi"
            cpu: "0m"
        env:
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: nvideo-db-secret
              key: password
              optional: false
        - name: POSTGRES_USER
          valueFrom:
            secretKeyRef:
              name: nvideo-db-secret
              key: user
              optional: false
        - name: POSTGRES_DB
          valueFrom:
            secretKeyRef:
              name: nvideo-db-secret
              key: db-name
              optional: false
        volumeMounts:
        - name:  postgres-data
          mountPath: /var/lib/postgresql/data
      volumes:
      - name: postgres-data
        persistentVolumeClaim:
          claimName: nvideo-postgres-pvc