apiVersion: monitoring.coreos.com/v1
kind: PodMonitor
metadata:
  name: nvideo-api-monitor
spec:
  selector:
    matchLabels:
      app: nvideo-api
  podMetricsEndpoints:
  - port: api
    path: /metrics
    interval: 10s