apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: nvideo-api-monitor
spec:
  selector:
    matchLabels:
      app: nvideo-api
  endpoints:
  - port: api
    path: /metrics
    interval: 10s
